#!/usr/bin/env ruby

name = File.basename(ARGV[0],".tex")



deps = []
bibdb = ""

reg = /\{([^\}]*)\}/


if !`grep '^[^%]*\\tableofcontents' #{ARGV[0]}`.strip.empty? then
	deps << "#{name}.toc"
end

if !`grep '^[^%]*\\listoffigures' #{ARGV[0]}`.strip.empty? then
	deps << "#{name}.lof"
end

if !`grep '^[^%]*\\printindex' #{ARGV[0]}`.strip.empty? then
	deps << "#{name}.ind"
end

if !`grep '^[^%]*\\printglossary' #{ARGV[0]}`.strip.empty? then
	deps << "#{name}.gls"
end

if !`grep '^[^%]*\\printnomenclature' #{ARGV[0]}`.strip.empty? then
	deps << "#{name}.nls"
end

bibliography = `grep '^[^%]*\\bibliography' #{ARGV[0]}`.strip
puts bibliography.inspect
if !bibliography.empty? then
	puts "Citations!"
	deps << "#{name}.bbl"
	
	bibdb = reg.match(bibliography).match[1]
	if bibdb =~ /\.bib$/ then
		bibdb << ".bib"
	end
	
	deps << bibdb
end

puts bibdb


figures = `grep '^[^%]*\\includegraphics' #{ARGV[0]}`.lines.collect do |line|
 	reg.match(line)[1]
end

File.open(ARGV[2],'w') do |dep_file|
 	dep_file.write "#{ARGV[1]}: #{figures.join(' ')} #{deps.join(' ')}\n\n"
	# dep_file.write "#{name}.bbl: #{bibdb}\n"
end
